version: "3.7"

services:
  laravel:
    build: ./laravel
    container_name: laravel
    depends_on:
      - db
    volumes:
      - ./laravel/source:/var/www/laravel

  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - ./mariadb-data/init.sql:/docker-entrypoint-initdb.d/setup.sql
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db

  nginx:
    depends_on:
      - db
      - laravel
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 7979:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./laravel/source/:/var/www/laravel/
volumes:
    mariadb_data: